var package_version = new Version("0.2");
var unity_version = "Unity 2018.2.10f1 (64-bit)";
var cef_version = "102.0.10+gf249b2e+chromium-102.0.5005.115";
var cef_branch = "5005";
var cefglue_branch = "5005";
var cef_download_dir = ""; //Choose short path (less than 35 characters)
var git_name = "";
var git_mail = "";
var pythonPath = string.Empty;
var msbuild_verbosity = Verbosity.Quiet;
var skip_update = false;
var skip_cef_build = false;
