var unity_version = "Unity 2018.2.8f1 (64-bit)";
var cef_version = "3.3497.1829.g004ef91";
var cef_branch = "3497";
var cefglue_branch = "3497";
var cef_download_dir = ""; //Choose short path (less than 35 characters)
var git_name = "";
var git_mail = "";
var python27_path = "";
var msbuild_verbosity = Verbosity.Quiet;
var skip_update = false;
var skip_cef_build = false;
